# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH/custom/plugins/
plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="${HOME}/.local/bin:${PATH}"

# Basic aliases
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias vi='nvim'
alias vim='nvim'
