source = ~/.config/hypr/current_lock.conf

general {
    hide_cursor = true
    immediate_render = true
}

animations {
    enabled = true
    bezier = smooth, 0.05, 0.9, 0.1, 1.0
    animation = fadeIn, 1, 4, smooth
    animation = fadeOut, 1, 4, smooth
}

background {
    monitor =
    path = $lock_wallpaper
    blur_passes = 3
    blur_size = 8
    color = $lock_inner
}

label {
    monitor =
    text = $TIME
    color = $lock_fg
    font_size = 72
    font_family = $lock_font
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = $lock_fg_dim
    font_size = 18
    font_family = $lock_font
    position = 0, 115
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    inner_color = $lock_inner
    outer_color = $lock_outer
    check_color = $lock_check
    fail_color = $lock_fail
    font_color = $lock_fg
    font_family = $lock_font
    placeholder_text = Password for $USER
    fail_text = $PAMFAIL
    fade_on_empty = false
    rounding = 12
    position = 0, -30
    halign = center
    valign = center
}
