$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    immediate_render = true
}

animations {
    enabled = true
    bezier = smooth, 0.05, 0.9, 0.1, 1.0
    animation = fadeIn, 1, 4, smooth
    animation = fadeOut, 1, 4, smooth
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = $TIME
    color = rgb(cdcecf)
    font_size = 72
    font_family = $font
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgb(738091)
    font_size = 18
    font_family = $font
    position = 0, 115
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    inner_color = rgba(192330dd)
    outer_color = rgb(719cd6)
    check_color = rgb(81b29a)
    fail_color = rgb(c94f6d)
    font_color = rgb(cdcecf)
    font_family = $font
    placeholder_text = Password for $USER
    fail_text = $PAMFAIL
    fade_on_empty = false
    rounding = 12
    position = 0, -30
    halign = center
    valign = center
}
