-- ==============================================================================
-- Hyprland Native Lua Configuration - Catppuccin Macchiato Theme
-- ==============================================================================

autogenerated = false

-- -- Autostart Services --------------------------------------------------------
hl.on("hyprland.start", function ()
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("spice-vdagent")
end)

-- -- Input & Keyboard Layout (Portuguese) --------------------------------------
input = {
    kb_layout = "pt",
    follow_mouse = 1,
    touchpad = {
        natural_scroll = false
    },
    sensitivity = 0
}

-- -- General Appearance --------------------------------------------------------
general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
    col_active_border = "rgba(89b4faee) rgba(cba6f7ee) 45deg",
    col_inactive_border = "rgba(313244aa)",
    layout = "dwindle"
}

-- -- Keybindings ---------------------------------------------------------------
-- SUPER + Q -> kitty
-- SUPER + R -> rofi
-- SUPER + C -> kill active
-- SUPER + V -> toggle floating
-- SUPER + M -> exit hyprland
