# Generated defaults; reconfigure with ~/.config/scripts/desktop-settings
input {
    kb_layout = pt
    kb_variant =
    kb_model =
    kb_options =
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}
