# Starship Prompt Configuration

format = "$username$directory$git_branch$git_status$cmd_duration$character"

add_newline = false

[username]
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[character]
success_symbol = "[›](bold green) "
error_symbol = "[›](bold red) "
vimcmd_symbol = "[‹](bold yellow) "

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only = " [RO]"
format = "[$path]($style) "

[git_branch]
style = "bold purple"
format = "on [$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "="
ahead = "^${count}"
behind = "v${count}"
diverged = "^${ahead_count}v${behind_count}"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[cmd_duration]
min_time = 2_000
format = "took [$duration] "
