foreground            #cdcecf
background            #192330
selection_foreground  #cdcecf
selection_background  #2b3b51
cursor                #719cd6
cursor_text_color     #192330

color0 #212e3f
color8 #39506d
color1 #c94f6d
color9 #d16983
color2  #81b29a
color10 #8ebd9d
color3  #dbc074
color11 #e0c989
color4  #719cd6
color12 #86abdc
color5  #9d79d6
color13 #aa8bdc
color6  #63cdcf
color14 #74d4d6
color7  #dfdfe0
color15 #aeafb0
